export enum ETelas {
    CONTROLE_ACESSO = "CONTROLE_ACESSO",
    CONTROLE_VEICULO = "CONTROLE_VEICULO",
    CONTROLE_PONTO = "CONTROLE_PONTO",
    VEICULO = "VEICULO",
    USUARIOS = "USUARIOS",
    VISITANTE = "VISITANTE",
}